### ISSUE TITLE
import csv

### ISSUE THREAD

**Issue by me3003** [ibd-diary/mobile-app#5]
Thank you for csv exporting.
I had to reinstall program and wanted to import it, but there was no option to do it.
could you improve?

**Comment by ibd-diary** [comment]
Thanks for the feedback.

The proposed approach for such scenarios (e.g., re-installation) is to use the Synchronization feature. Just synchronize the diary data before removal and start with the existing diary after the (re-)installation.

There are many reasons why we don't offer a import feature. The most important one is the relatively large maintenance effort compared to the benefit of the feature. We would have to ensure that the import feature is compatible with the export format of every release of our app.
