### ISSUE TITLE
report zoom/range

### ISSUE THREAD

**Issue by me3003** [ibd-diary/mobile-app#6]
It would be nice to be able to select a range larger than 30 days or have the possibility to zoom in/out the range.

**Comment by ibd-diary** [comment]
Thanks for the feedback.

The time range in the mobile app is computed based on the screen resolution/size. 
Greater resolution/screen -> more larger time range.

However, the upcoming release of the mobile app supports the export to IBD Clipboard, which offers individual/larger time ranges.
